### PR TITLE
[WIP][MIG] webkit-tools, again

### PR DESCRIPTION
**Pull request by charbeljc**

### CODE REVIEW

**Comment by nbessi** [comment]
:+1:

**Comment by vrenaville** [comment]
@charbeljc why do you start a new PR instead of improving this one https://github.com/OCA/webkit-tools/pull/10

**Comment by vrenaville** [comment]
It's seems to be more complete (README.rst) instead of  https://github.com/OCA/webkit-tools/pull/10
so :+1:

**Comment by mdietrichc2c** [comment]
:+1:

**Comment by charbeljc** [comment]
Hi @vrenaville , to answer to your question, this PR is already one month old, I did it this way instead of improving #10 by lack of github experience.  Regards

**Pull request merged**
