### PR TITLE
Add webkit setup module

### PR DESCRIPTION
**Pull request by ntodorova**
This module allows to configure the webkit path by a wizard during setup.
All wkhtmltopdf binaries in the PATH will be suggested in the wizard
drop down field.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Isn't better to have this configuration as a permanent parameter in configuration instead of a wizard?

**Comment by OSguard** [comment]
the wizard is to easy find the correct value for "webkit_path" and store it to "ir.config_parameter"

**Comment by lepistone** [comment]
I am not enthusiastic about adding application code to do server configuration. I'm not blocking it though. Thanks!

**Comment by ovnicraft** [comment]
Its server configuration, but ir.parameters is not in DB ? 

Wizard is helping to do this.

**Comment by pedrobaeza** [comment]
Travis is still red and no further development, so I close this. If there's still interest in this, feel free to open a new PR fixing Travis.

**Pull request closed without merging**
